version: "3.3"

services:
  move-log:
    image: evolveum/midpoint:${MP_VER:-latest}-alpine
    command: >
        bash -c "
        cd /opt/midpoint/var ;
        mkdir logs ;
        if [ -e log ] ;
        then mv log logs/node1 ;
        else mkdir logs/node1 ;
        fi ;
        ln -s logs/node1 log ;
        echo 'Log directory hase been moved...' ;
        "
    volumes:
     - midpoint_home:/opt/midpoint/var

  add-cert:
    image: evolveum/midpoint:${MP_VER:-latest}-alpine
    command: >
        bash -c "
        keytool -keystore /opt/midpoint/var/keystore.jceks -storetype jceks -storepass changeit -import -alias letsencryptroot -trustcacerts -file /tmp/cert.pem -noprompt;
        echo ' - - - - - - - -';
        keytool -list -keystore /opt/midpoint/var/keystore.jceks -storetype jceks -storepass changeit ;
        "
    volumes:
     - midpoint_home:/opt/midpoint/var
     - ./ISRG_root_x1.pem:/tmp/cert.pem

  del-cert:
    image: evolveum/midpoint:${MP_VER:-latest}-alpine
    command: >
        bash -c "
        keytool -keystore /opt/midpoint/var/keystore.jceks -storetype jceks -storepass changeit -delete -alias letsencryptroot -noprompt;
        echo ' - - - - - - - -';
        keytool -list -keystore /opt/midpoint/var/keystore.jceks -storetype jceks -storepass changeit ;
        "
    volumes:
     - midpoint_home:/opt/midpoint/var


  add-ssh:
    image: evolveum/midpoint:${MP_VER:-latest}-alpine
    command: >
        bash -c "
        ls -la /opt/midpoint/var/connid-connectors ; 
        echo ' - - - - - - - -' ; 
        cp /tmp/connector-ssh-1.0.jar /opt/midpoint/var/connid-connectors ; 
        ls -la /opt/midpoint/var/connid-connectors ;
        "
    volumes:
     - midpoint_home:/opt/midpoint/var
     - ./connector-ssh-1.0.jar:/tmp/connector-ssh-1.0.jar

volumes:
  midpoint_home:
